= Accounting 101

.Table Class Webcasts
|===
|Item | Session webcast | Short Description | Supplementary Material

| Preview
| https://www.youtube.com/watch?v=Jbp3-AU9v_g[Introduction to sessions]
| Provides an introduction to (my) version of an accounting class. Perhaps, more a warning, than a sales pitch!
|

|1
|https://www.youtube.com/watch?v=7rW7lpQZpqY[Financial Statements: An Overview]
|Provides an overview of the three financial statements and what they aim to do (and sometimes fail to do).
|

* http://people.stern.nyu.edu/adamodar/pdfiles/Accounting101/slides/session1.pdf[slides]

| 2
| https://www.youtube.com/watch?v=Q8wKr1QDSwg[Income Statements: Measuring Profits]
| Go through an income statement, drawing distinctions between operating & financing expenses and measures of profitability.
|

* http://people.stern.nyu.edu/adamodar/pdfiles/Accounting101/slides/session2.pdf[slides]
* http://people.stern.nyu.edu/adamodar/pdfiles/Accounting101/postclass/session2test.pdf[Post-class test] & http://people.stern.nyu.edu/adamodar/pdfiles/Accounting101/postclass/session2soln.pdf[solution]

| 2A
| https://www.youtube.com/watch?v=UYxJl2GvdGw[Income Statements: Illustrations]
| Look at the income statements of a diverse set of companies, at different stages of life cycle and in different sectors.
|
http://people.stern.nyu.edu/adamodar/pdfiles/Accounting101/slides/session2A.pdf[Slides]
http://people.stern.nyu.edu/adamodar/pdfiles/Accounting101/postclass/session2Atest.pdf[Post-class test] & http://people.stern.nyu.edu/adamodar/pdfiles/Accounting101/postclass/session2Asoln.pdf[solution]

| 3
| https://youtu.be/cSuc2HHQpxc[Balance Sheets: Asset Base and Debt Due]
| Go through a balance sheet, looking at how assets get recorded on it, and how that measurement affects accounting measures of equity.
|
 http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/slides/session3.pdf[Slides]
http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session3test.pdf[Post-class test] & http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session3soln.pdf[solution]

| 3A
| https://youtu.be/Gr4JwDB1iRM[Balance Sheets: Illustrations]
| Look at the balance sheets of a diverse set of companies, at different stages of life cycle and in different sectors.
|
http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/slides/session3A.pdf[Slides]
http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session3Atest.pdf[Post-class test] & http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session3Asoln.pdf[solution]

| 4
| https://youtu.be/XobT12fvkXc[Cashflow Statements: Cash In and Out]
| Go through a cash flow statement, drawing out information that it provides on cash earnings and cash flows.
|

http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/slides/session4.pdf[Slides]
http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session4test.pdf[Post-class test] & http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session4soln.pdf[solution]


| 4A
| https://youtu.be/U954oEU7_0w[Cash Flow Statements: Illustrations]
| Look at the cashflow statements of a diverse set of companies, at different stages of life cycle and in different sectors.
|

http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/slides/session4A.pdf[Slides]
http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session4Atest.pdf[Post-class test] & http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session4Asoln.pdf[solution]


| 5
| https://youtu.be/un6-H_wOizM[Accounting Inconsistencies & Consequences]
| Look at the items (stock based compensation, R&D, leases) where there are accounting inconsistencies, and how they play out in the statements.

|

http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/slides/session5.pdf[Slides]
http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session5test.pdf[Post-class test] & http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session5soln.pdf[solution]


| 5A
| https://youtu.be/o4_GwR_6jR4[Accounting Inconsistencies: Illustrations]
| Look at the how to resolve inconsistencies in accounting in real-world examples.
|

http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/slides/session5A.pdf[Slides]
http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session5Atest.pdf[Post-class test] & http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session5Asoln.pdf[solution]


| 6
| https://youtu.be/ZXXF-rSaE9E[Financial Ratios: Of comps and peer groups]
| Ratios are scaling mechanisms, allowing for comparisons across companies and across time. In this session, I look at a range of ratios that can help in analysis.

|

http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/slides/session6.pdf[Slides]
http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session6test.pdf[Post-class test] & http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session6soln.pdf[solution]


| 6A
| https://youtu.be/pL2wIDWXN68[Financial Ratios: Illustrations]
| Look at using financial ratios to make judgments about profitability, leverage and liquidity with real-world examples.

|

http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/slides/session6A.pdf[Slides]
http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session6Atest.pdf[Post-class test] & http://www.stern.nyu.edu/~adamodar/pdfiles/Accounting101/postclass/session6Asoln.pdf[solution]

|===


Reference:
http://pages.stern.nyu.edu/~adamodar/New_Home_Page/webcastacctg.htm
